name = "OpenAI"
uuid = "e9f21f70-7185-4079-aca2-91159181367c"
authors = [
    "Rory Linehan @rory-linehan",
    "Marius Fersigan @algunion",
    "RexWzh @RexWzh",
    "Thatcher Chamberlin @ThatcherC",
    "Nicu Stiurca @nstiurca",
    "Peter @chengchingwen",
    "Stefan Wojcik @stefanjwojcik",
    "J S @svilupp",
    "Logan Kilpatrick @logankilpatrick",
    "Jerry Ling @Moelf"
]
version = "0.8.6"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"

[compat]
HTTP = "1"
JSON3 = "1.12"
julia = "1"

[extras]
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["JET", "Pkg", "Test"]
